// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgeaF943vwSoHKSuO2lMkGdhlBu6VEae0',
    appId: '1:337193124490:web:f6a0ab7b9f17df4399e373',
    messagingSenderId: '337193124490',
    projectId: 'newsit-app',
    authDomain: 'newsit-app.firebaseapp.com',
    storageBucket: 'newsit-app.appspot.com',
    measurementId: 'G-5R8FMKH0X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdgiNVWiekzfmnGQ8pRrbyCLM5bqxVz2c',
    appId: '1:337193124490:android:ff149850efeb864d99e373',
    messagingSenderId: '337193124490',
    projectId: 'newsit-app',
    storageBucket: 'newsit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkE8GqMg99lHq9TwlPZH-j_77U45u2R7w',
    appId: '1:337193124490:ios:2a493bad9ce75e9199e373',
    messagingSenderId: '337193124490',
    projectId: 'newsit-app',
    storageBucket: 'newsit-app.appspot.com',
    androidClientId: '337193124490-ar3tkc44eadstoovi7e723p058vpdrp0.apps.googleusercontent.com',
    iosClientId: '337193124490-ijkk6tjssol9khh1hb7latnh8uivsb99.apps.googleusercontent.com',
    iosBundleId: 'com.newsit.read',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkE8GqMg99lHq9TwlPZH-j_77U45u2R7w',
    appId: '1:337193124490:ios:2a493bad9ce75e9199e373',
    messagingSenderId: '337193124490',
    projectId: 'newsit-app',
    storageBucket: 'newsit-app.appspot.com',
    androidClientId: '337193124490-ar3tkc44eadstoovi7e723p058vpdrp0.apps.googleusercontent.com',
    iosClientId: '337193124490-ijkk6tjssol9khh1hb7latnh8uivsb99.apps.googleusercontent.com',
    iosBundleId: 'com.newsit.read',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgeaF943vwSoHKSuO2lMkGdhlBu6VEae0',
    appId: '1:337193124490:web:7b044700d1e73b5a99e373',
    messagingSenderId: '337193124490',
    projectId: 'newsit-app',
    authDomain: 'newsit-app.firebaseapp.com',
    storageBucket: 'newsit-app.appspot.com',
    measurementId: 'G-5REX5R8W4Q',
  );
}
